spring.application.name=proyectofinal
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/proyectofinal}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8081

jwt.secret=${JWT_SECRET:dev-secret-change-me-please-1234567890-dev-secret}

gemini.api-key=${GEMINI_API_KEY:AIzaSyDzjeavgpHk7-sc6usRS1plsn8UC_9Eac8}
gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}

agora.app-id=${AGORA_APP_ID:}
agora.app-certificate=${AGORA_APP_CERTIFICATE:}

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api_key=${CLOUDINARY_API_KEY:}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=https://localhost:4200
