spring.application.name=proyectofinal

spring.datasource.url=jdbc:mysql://5.tcp.ngrok.io:29865/base45
spring.datasource.username=estudiantedes3
spring.datasource.password=desarrollo2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=8081

jwt.secret=reload-prod-jwt-secret-2026-geovanny-riano-unbosque-4f7c92a1b6d84e11a3ce59fdb2786c40

# GEMINI IA
gemini.api-key=${GEMINI_API_KEY:}
gemini.base-url=https://generativelanguage.googleapis.com
gemini.model=gemini-2.5-flash

# AGORA
agora.app-id=${AGORA_APP_ID:}
agora.app-certificate=${AGORA_APP_CERTIFICATE:}

# CLOUDINARY
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api_key=${CLOUDINARY_API_KEY:}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:}

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.mail.test-connection=false

# ARCHIVOS
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB

# FRONTEND
app.frontend.url=https://reload-pc.netlify.app
app.frontend.allowed-origins=https://reload-pc.netlify.app,https://reload-celular.netlify.app,http://localhost:4200,http://localhost:4201
app.mail.from=${MAIL_FROM:}

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persistAuthorization=true
springdoc.api-docs.path=/v3/api-docs
