spring.application.name=proyectofinal

spring.datasource.url=jdbc:mysql://5.tcp.ngrok.io:29865/base45
spring.datasource.username=estudiantedes3
spring.datasource.password=desarrollo2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=8081

jwt.secret=${JWT_SECRET:dev-secret-change-me-please-1234567890-dev-secret}

# GEMINI IA
gemini.api-key=${GEMINI_API_KEY:AIzaSyCN108nSvj2QQ5MF6YMLfrS0a8JpC1l-yE}
gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}

# AGORA
agora.app-id=${AGORA_APP_ID:}
agora.app-certificate=${AGORA_APP_CERTIFICATE:}

# CLOUDINARY
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api_key=${CLOUDINARY_API_KEY:}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:}

# MAIL
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${SPRING_MAIL_STARTTLS_REQUIRED:true}
spring.mail.properties.mail.smtp.connectiontimeout=${SPRING_MAIL_CONNECTION_TIMEOUT:5000}
spring.mail.properties.mail.smtp.timeout=${SPRING_MAIL_TIMEOUT:5000}
spring.mail.properties.mail.smtp.writetimeout=${SPRING_MAIL_WRITE_TIMEOUT:5000}

spring.mail.test-connection=${SPRING_MAIL_TEST_CONNECTION:false}

# FRONTEND
app.frontend.url=${APP_FRONTEND_URL:http://localhost:4200}
app.mail.from=${MAIL_FROM:${SPRING_MAIL_USERNAME:}}

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persistAuthorization=true
springdoc.api-docs.path=/v3/api-docs